version: "3.8"

services:
  glucose-monitor:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "53000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    container_name: glucose-monitor
